ARG NODE_IMAGE=node:20-alpine
ARG NGINX_IMAGE=nginx:stable-alpine
FROM ${NODE_IMAGE} AS build

WORKDIR /usr/src
RUN npm install -g turbo
# Copy the root package.json AND package-lock.json
COPY package*.json ./
# Copy all files
COPY . .
# Install necessary global tools and dependencies
RUN npm install

ARG VITE_APP_BASE_URL

# Set environment variables for the build process
ENV VITE_APP_BASE_URL=${VITE_APP_BASE_URL}

# Build the front-end with the VITE_API_URL environment variable
RUN npm run build:web

# Stage 2: Serve static files and API with Nginx
FROM ${NGINX_IMAGE} AS production

# Copy static files to serve via Nginx
COPY --from=build /usr/src/apps/web/dist /usr/share/nginx/html

# Copy the Nginx configuration file for reverse proxy
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# Expose the port
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]